### ISSUE TITLE
Automatically fill size

### ISSUE THREAD

**Issue by dustinlacewell** [JureSotosek/ink-divider#9]
Do you think you could use the measureElement API to make this fill the available space?

**Comment by okineadev** [comment]
> Do you think you could use the measureElement API to make this fill the available space?

Just use this:

```jsx
import type React from 'react'
import { Box, type BoxProps } from 'ink'

/**
 * Props for the Divider component.
 */
export interface DividerProps extends BoxProps {
	/**
	 * Color of the divider's border. Matches the type of `borderColor` in the Ink `Box` component.
	 * Accepts standard Ink color names or hex codes.
	 * @default "blackBright"
	 */
	color?: BoxProps['borderColor']
}

/**
 * A horizontal divider component styled as a single border line.
 *
 * @param props - Properties to customize the divider.
 * @returns A styled Ink `Box` component representing a divider.
 */
const Divider: React.FC<DividerProps> = ({
	color = 'blackBright',
	...props
}) => (
	<Box
		borderColor={color}
		borderStyle="single"
		borderBottom={true}
		borderTop={false}
		borderLeft={false}
		borderRight={false}
		{...props}
	/>
)
```

I think in the near future I will create an updated module with automatic expansion of the Divider width on npm

**Comment by okineadev** [comment]
@JureSotosek Do you accept PRs to this repository?

**Comment by JureSotosek** [comment]
Yes, make a PR and i'll merge it.

**Comment by okineadev** [comment]
> Yes, make a PR and i'll merge it.

I thought this project was completely dead... 😅

Ok, my plan is to make it work in ink, rewrite the Divider logic so that it now works based on the Box component (as in the comment above) and also make it backwards compatible with existing projects so I don't break anything

If I don't have time to do it today, I'll finish it on Monday

**Comment by JureSotosek** [comment]
Awesome, thanks 😀

**Comment by okineadev** [comment]
> Awesome, thanks 😀

And another question

Should I use this stack?

- Bun (https://bun.sh) for building package
- TypeScript
- Biome formatter

**Comment by JureSotosek** [comment]
@okineadev  If you make it with bun will it still be 100% compatible with node?

**Comment by okineadev** [comment]
> @okineadev If you make it with bun will it still be 100% compatible with node?

Yes, because the source file will be compiled in Node format, so this module will work on both Node and Bun

For developers, the project will use Bun, so you need to install Bun to build the project (takes 10 seconds)

Bun is a drop-in replacement for Node, it's a (really fast) package manager, bundler and test runner all in one!

It can be used by anyone who has used npm, yarn or pnpm thanks to commands familiar to all

Here is an example of how to install the package:

```bash
bun i package
bun install package
bun add package
```

**Comment by JureSotosek** [comment]
@okineadev Sure lets do that.

**Comment by JureSotosek** [comment]
@okineadev Sent you a message on X!
